In [1]:
from keras.models import Sequential
from keras.layers.core import Flatten, Dense, Dropout
from keras.layers.convolutional import Convolution2D, MaxPooling2D, ZeroPadding2D
from keras.layers import Conv2D
from keras.optimizers import SGD
import cv2 
import numpy as np

Using TensorFlow backend.


In [2]:
import os

In [3]:

def generator_train(type_data):
    label=np.array([])
    train_data=np.array([])
    if type_data=='train':
        work_dir=os.listdir('/home/crdr/Plant Seeding Classification/train_test_dataset/train')
        for w in work_dir:
            print(w)
            for u in os.listdir('/home/crdr/Plant Seeding Classification/train_test_dataset/train/'+w):
                label=np.append(label,w)
                
                im=cv2.resize(cv2.imread('/home/crdr/Plant Seeding Classification/train_test_dataset/train/'+w+'/'+u), (112, 112))
                im[:,:,0] -= 103
                im[:,:,1] -= 116
                im[:,:,2] -= 123
                im = im.transpose((2,0,1))
                im = np.expand_dims(im, axis=0)
                train_data=np.append(train_data,im)
        return train_data,label
    if type_data=='test':
        work_dir=os.listdir('/home/crdr/Plant Seeding Classification/train_test_dataset/test')
        

In [ ]:
def VGG_16(weights_path=None):
    model = Sequential()
    model.add(ZeroPadding2D((1,1),input_shape=(3,112,112)))
    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(MaxPooling2D((1,1), strides=(1,1)))
    
    
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(128, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(128, (3, 3), activation='relu'))
    model.add(MaxPooling2D((1,1), strides=(1,1)))
    
    
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(256, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(256, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(256, (3, 3), activation='relu'))
    model.add(MaxPooling2D((1,1), strides=(1,1)))
    
    
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(512, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(512, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(512, (3, 3), activation='relu'))
    model.add(MaxPooling2D((1,1), strides=(1,1)))

    
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(512, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(512, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(512, (3, 3), activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))
    model.add(Flatten())
    model.add(Dense(4096, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(4096, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(1000, activation='relu'))
    model.add(Dense(12,activation='softmax'))
   
    if weights_path:
        model.load_weights(weights_path,by_name=True)
    return model

In [5]:
X,labels=generator_train('train')


Shepherds Purse
Small-flowered Cranesbill
Sugar beet
Black-grass
Common wheat
Common Chickweed
Scentless Mayweed
Loose Silky-bent
Cleavers
Maize
Charlock
Fat Hen


In [6]:
X_train=np.reshape(X,(4750,3,112,112))

In [7]:
X_train.shape

(4750, 3, 112, 112)

In [8]:
print(labels)

['Shepherds Purse' 'Shepherds Purse' 'Shepherds Purse' ... 'Fat Hen'
 'Fat Hen' 'Fat Hen']


In [9]:
import keras

In [10]:
from sklearn import preprocessing

In [11]:
le = preprocessing.LabelEncoder()

In [12]:
le.fit(labels)

LabelEncoder()

In [13]:
list(le.classes_)

['Black-grass',
 'Charlock',
 'Cleavers',
 'Common Chickweed',
 'Common wheat',
 'Fat Hen',
 'Loose Silky-bent',
 'Maize',
 'Scentless Mayweed',
 'Shepherds Purse',
 'Small-flowered Cranesbill',
 'Sugar beet']

In [14]:
le.transform(le.classes_) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
print(le)

LabelEncoder()


In [16]:
from sklearn.preprocessing import LabelBinarizer

In [17]:
encoder = LabelBinarizer()
transfomed_label = encoder.fit_transform(labels)
print(transfomed_label)

[[0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
transfomed_label.shape

(4750, 12)

In [19]:
import tensorflow as tf

In [30]:
if __name__ == "__main__":
    TF_CONFIG_ = tf.ConfigProto()
    TF_CONFIG_.gpu_options.allow_growth = True
    sess = tf.Session(config = TF_CONFIG_)
    '''
    im = cv2.resize(cv2.imread('/home/crdr/Plant Seeding Classification/train_test_dataset/train/Black-grass/0ace21089.png'), (224, 224)).astype(np.float32)
    im[:,:,0] -= 103.939
    im[:,:,1] -= 116.779
    im[:,:,2] -= 123.68
    im = im.transpose((2,0,1))
    im = np.expand_dims(im, axis=0)
    print(im.shape)
    # Test pretrained model
    '''
    model = VGG_16('/home/crdr/Plant Seeding Classification/vgg16_weights.h5')
    sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
    model.compile(optimizer=sgd, loss='categorical_crossentropy')
    n_batch=16
    #model.fit(X_train, transfomed_label, epochs=60, batch_size=n_batch)#, verbose=1, shuffle=False)
    
    
    

In [25]:
    #model.save_weights('plant_seed_weight.h5')

In [31]:
#model = VGG_16('/home/crdr/Plant Seeding Classification/vgg16_weights.h5')
model.load_weights('plant_seed_weight.h5')
im = cv2.resize(cv2.imread('/home/crdr/Plant Seeding Classification/train_test_dataset/train/Black-grass/0ace21089.png'), (112, 112))
im[:,:,0] -= 103
im[:,:,1] -= 116
im[:,:,2] -= 123
im = im.transpose((2,0,1))
im = np.expand_dims(im, axis=0)
prmodel.predict(im)

ResourceExhaustedError: OOM when allocating tensor with shape[28672,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: dense_33/random_uniform/RandomUniform = RandomUniform[T=DT_INT32, dtype=DT_FLOAT, seed=87654321, seed2=5539210, _device="/job:localhost/replica:0/task:0/device:GPU:0"](dense_33/random_uniform/shape)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op u'dense_33/random_uniform/RandomUniform', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelapp.py", line 497, in start
    self.io_loop.start()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 1073, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2714, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2818, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-f6429169a90d>", line 15, in <module>
    model = VGG_16('/home/crdr/Plant Seeding Classification/vgg16_weights.h5')
  File "<ipython-input-4-1f8c256f7e71>", line 43, in VGG_16
    model.add(Dense(4096, activation='relu'))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/sequential.py", line 185, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 861, in build
    constraint=self.kernel_constraint)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 249, in add_weight
    weight = K.variable(initializer(shape),
  File "/usr/local/lib/python2.7/dist-packages/keras/initializers.py", line 218, in __call__
    dtype=dtype, seed=self.seed)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 4049, in random_uniform
    dtype=dtype, seed=seed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/random_ops.py", line 242, in random_uniform
    rnd = gen_random_ops.random_uniform(shape, dtype, seed=seed1, seed2=seed2)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_random_ops.py", line 732, in random_uniform
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[28672,4096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: dense_33/random_uniform/RandomUniform = RandomUniform[T=DT_INT32, dtype=DT_FLOAT, seed=87654321, seed2=5539210, _device="/job:localhost/replica:0/task:0/device:GPU:0"](dense_33/random_uniform/shape)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

